replicaCount: 1
image:
  repository: quay.io/volatilemolotov/xaccelerator
  tag: 0.0.2
  pullPolicy: Always
  pullSecret: god-docker-secret
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

config:
  backend: "http://helloworld-go"

    
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
